# Generated by Django 4.2.7 on 2024-01-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_userrecipe_likelycookingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipe',
            old_name='likelyCookingDate',
            new_name='cookingDate',
        ),
    ]
