# Generated by Django 4.2.7 on 2024-01-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_otheruser_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otheruser',
            name='role',
        ),
    ]
