# Generated by Django 4.2.7 on 2024-01-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_otheruser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='cookingDate',
        ),
    ]
