# Generated by Django 4.2.7 on 2024-01-04 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0009_alter_favorites_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'favoriteRecipe')},
        ),
    ]
