# Generated by Django 4.2.7 on 2023-12-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountNumber',
            field=models.IntegerField(default=1234567890),
        ),
    ]
